#!/usr/bin/env python3
import rclpy
from laser_scanner.map_merger import MapMergerNode

def main():
    rclpy.init()
    node = MapMergerNode()
    rclpy.spin(node)
    rclpy.shutdown()

if __name__ == '__main__':
    main()
