#!/usr/bin/env python3
import rclpy
from laser_scanner.scanning_coordinator import ScanningCoordinatorNode

def main():
    rclpy.init()
    node = ScanningCoordinatorNode()
    rclpy.spin(node)
    rclpy.shutdown()

if __name__ == '__main__':
    main()
