#!/usr/bin/env python3
import rclpy
from laser_scanner.scan_accumulator import ScanAccumulatorNode

def main():
    rclpy.init()
    node = ScanAccumulatorNode()
    rclpy.spin(node)
    rclpy.shutdown()

if __name__ == '__main__':
    main()
